name: Node CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ["14", "16", "18", "20"]
        os: [ubuntu-22.04, windows-2022, macOS-12]
        exclude:
          - os: windows-2022
            node-version: "14"

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install

    - name: Lint
      run: |
        npm run test:lint

    - name: Test
      run: |
        npm test

    - name: Type Definitions
      run: |
        npm run test:typescript
